language: en

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 50
    entity_recognition: False
  - name: ResponseSelector
    epochs: 50

policies:
   - name: RulePolicy
