version: '3'
services:
    nginx:
      container_name: "nginx"
      image: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
      ports:
        - 3005:3005
      depends_on: 
        - rasa
        - action_server
        - chatbot_ui
    rasa:
      container_name: "rasa_server"
      build: 
        context: backend
      ports: 
        - "5005:5005"
    action_server:
      container_name: "action_server"
      build: 
        context: action_server
      volumes:
        - ./action_server/test_data.json:/app/test_data.json
      ports:
        - "5055:5055"
    chatbot_ui:
      container_name: "chatbot_ui"
      build: 
        context: frontend
      ports: 
        - "3000:3000"


